import place_one from '../assets/images/place-1.jpg';

export const places = [
  {
    id: 1,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: '4.5',
    location: 'Hotel de Ville, Paris, France',
    description:
      'The Grand Budapest Hotel is a hotel and guest house in the city center of Paris, France. It is a mainstay of the high-class city of Paris and one of the most well-known symbols of the city. The hotel is a modernist style hotel with panoramic views of the city center.',
    distance: '4,234 Kilometers',
  },
  {
    id: 2,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: '4.5',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 3,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: '4.5',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 4,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: '4.5',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 5,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: '4.5',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 6,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: '4.5',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 7,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 8,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 9,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 10,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 11,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 12,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 13,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 14,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 15,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 16,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 17,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 18,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 19,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 20,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 21,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 22,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 23,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
  {
    id: 24,
    name: 'The Grand Budapest Hotel',
    image: place_one,
    date: 'Nov 9 -20',
    price: '$52.00',
    rating: 'New',
    location: 'Hotel de Ville, Paris, France',
    distance: '4,234 Kilometers',
  },
];
